name: Stock News Crawler

on:
  schedule:
    # 5분마다 실행 (GitHub Actions는 최소 5분)
    - cron: '*/5 * * * *'
  
  # 수동 실행 버튼
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - name: 체크아웃
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    
    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: 의존성 설치
      run: |
        pip install -r requirements.txt
    
    - name: 크롤링 실행
      run: |
        python src/main.py --mode once
    
    - name: 결과 확인
      run: |
        echo "=== 실행 완료 ==="
        ls -lh output/
        if [ -f "data/run_history.json" ]; then
          echo "=== 최근 실행 이력 ==="
          python view_history.py --limit 1
        fi
    
    - name: GitHub Pages 배포
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        keep_files: false
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: '🤖 Auto update: ${{ github.event.head_commit.message }}'
